name: Sync Template
on:
  # Uncomment the schedule for a weekly sync (Monday at 00:00 UTC)
  # schedule:
  #   - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is fetched

      - name: Set Up Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Upstream and Fetch Changes
        run: |
          git remote -v | grep 'upstream' || git remote add upstream https://github.com/GoogleCloudPlatformDevops/gcp-tf-modules.git
          git fetch upstream main

      - name: Merge Upstream Changes into Main
        run: |
          git checkout main
          git merge --ff-only upstream/main || echo "No changes to merge"
          git push origin main








# name: Release Workflow

# on:
#   push:
#     branches:    
#       - main

#   pull_request:


# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Create GitHub Release
#         uses: actions/create-release@v1
#         with:
#           tag_name: v1.0.0
#           release_name: Release v1.0.0
#           body: |
#             Description of the release
#           draft: false
#           prerelease: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.release }}
