name: Release Workflow

on:
  push:
    branches:    
      - main

  pull_request:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Description of the release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.release }}
